<a href="https://colab.research.google.com/github/skyworld19/ds-school-advanced/blob/master/ML_11_OneHot_LabelEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### LabelEncoder를 이용한 데이터 인코딩

In [ ]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
from pandas import DataFrame

In [ ]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환 {}'.format(labels))
#변환된 인코딩 확인
print('인코딩 클래스 : {}'.format(encoder.classes_))

인코딩 변환 [0 1 4 5 3 3 2 2]
인코딩 클래스 : ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [ ]:
arr1 = np.arange(1000,9000,1000)
data = {'상품':items,'price':arr1}
df = DataFrame(data)
df

상품  price
0     TV   1000
1    냉장고   2000
2  전자레인지   3000
3    컴퓨터   4000
4    선풍기   5000
5    선풍기   6000
6     믹서   7000
7     믹서   8000

In [ ]:
df['상품코드'] = labels
#재배치
df= df[['상품코드','상품','price']]
df

상품코드     상품  price
0     0     TV   1000
1     1    냉장고   2000
2     4  전자레인지   3000
3     5    컴퓨터   4000
4     3    선풍기   5000
5     3    선풍기   6000
6     2     믹서   7000
7     2     믹서   8000

In [ ]:
import seaborn as sns
tips = sns.load_dataset('tips')
tips.head(3)
tips['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [ ]:
encoder = LabelEncoder()
day_encoded = encoder.fit_transform(tips['day'])
day_encoded
tips['day'] = day_encoded
tips.head(3)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No    2  Dinner     2
1       10.34  1.66    Male     No    2  Dinner     3
2       21.01  3.50    Male     No    2  Dinner     3

In [ ]:
#역변환
inversed = encoder.inverse_transform(tips['day'])
inversed

array(['Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun',
       'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun',
       'Sun', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sun', 'Sun', 'Sun', 'Sun',
       'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun',
       'Sun', 'Sun', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Thur', 'Thur', 'Thur', 'Thur',
       'Thur', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur',
       'Thur', 'Fri', 'Fri', 'Fri', 'Fri', 'Fri', 'Fri', 'Fri', 'Fri',
       'Fri', 'Fri', 'Fri', 'Fri', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sun', 'Sun', 'Sun', 'Sun',
       'Sun', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur',
       'Thur',

### 다른 방법

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr1 = np.arange(1000,9000,1000)
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
data = {'상품':items,'price':arr1}
df = pd.DataFrame(data)
df

상품  price
0     TV   1000
1    냉장고   2000
2  전자레인지   3000
3    컴퓨터   4000
4    선풍기   5000
5    선풍기   6000
6     믹서   7000
7     믹서   8000

In [ ]:
# replace



In [ ]:
# category의 cat.codes


### One_Hot Encoding

In [ ]:
import numpy as np
import pandas as pd
from pandas import DataFrame
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

C:\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [ ]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
#숫자값 변환을 위해 LabelEncoder 이용
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)
#2차원에서 -1은 행또는 열의 갯수를 지정해 주고 나머지를 2차원으로 만든다
#아래는 열의 갯수가 1이므로 8행 1열의 2차원 데이터를 만든다
labels2D = labels.reshape(-1,1)
labels2D

[0 1 4 5 3 3 2 2]


array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]], dtype=int64)

In [ ]:
#One-Hot Encoding 적용 (2차원 데이터가 필요함)
one_encoder = OneHotEncoder()
one_encoder.fit(labels2D)
one_labels = one_encoder.transform(labels2D)
print(one_labels)
print(one_labels.toarray())
print('차원', one_labels.shape)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
차원 (8, 6)


C:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [ ]:
##Pandas의 getDummies()를 이용한 One-Hot Encoding
df = DataFrame({'item':items})
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [ ]:
#판다스의 get_dummies 사용시 숫자로 변환없이도 원핫 인코딩이 가능하다. 
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0