<a href="https://colab.research.google.com/github/skyworld19/ds-school-advanced/blob/master/ML_11_OneHot_LabelEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### LabelEncoder를 이용한 데이터 인코딩

In [ ]:
"""
LabelEncoding을 할 때 주로 사용하는 방법
- s.replace
- category 타입의 cat.code 
"""

In [1]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
from pandas import DataFrame

In [2]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환 {}'.format(labels))
#변환된 인코딩 확인
print('인코딩 클래스 : {}'.format(encoder.classes_))

인코딩 변환 [0 1 4 5 3 3 2 2]
인코딩 클래스 : ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [3]:
arr1 = np.arange(1000,9000,1000)
data = {'상품':items,'price':arr1}
df = DataFrame(data)
df

상품  price
0     TV   1000
1    냉장고   2000
2  전자레인지   3000
3    컴퓨터   4000
4    선풍기   5000
5    선풍기   6000
6     믹서   7000
7     믹서   8000

In [4]:
df['상품코드'] = labels
#재배치
df= df[['상품코드','상품','price']]
df

상품코드     상품  price
0     0     TV   1000
1     1    냉장고   2000
2     4  전자레인지   3000
3     5    컴퓨터   4000
4     3    선풍기   5000
5     3    선풍기   6000
6     2     믹서   7000
7     2     믹서   8000

In [5]:
import seaborn as sns
tips = sns.load_dataset('tips')
tips.head(3)
tips['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [8]:
# day 변환
encoder = LabelEncoder()
day_encoded = encoder.fit_transform(tips['day'])
day_encoded

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [9]:
tips['day'] = day_encoded
tips.head(3)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No    2  Dinner     2
1       10.34  1.66    Male     No    2  Dinner     3
2       21.01  3.50    Male     No    2  Dinner     3

In [11]:
# time 변환
encoder2 = LabelEncoder()
tips['time_code'] = encoder2.fit_transform(tips['time'])
tips.head(3)

total_bill   tip     sex smoker  day    time  size  day_code  time_code
0       16.99  1.01  Female     No    2  Dinner     2         2          0
1       10.34  1.66    Male     No    2  Dinner     3         2          0
2       21.01  3.50    Male     No    2  Dinner     3         2          0

In [14]:
# smoker 변환
tips['smoker'].unique()
tips['smoker'].replace({'No':0, 'Yes':1}, inplace=True)
tips.head(3)

total_bill   tip     sex  smoker  day    time  size  day_code  time_code
0       16.99  1.01  Female       0    2  Dinner     2         2          0
1       10.34  1.66    Male       0    2  Dinner     3         2          0
2       21.01  3.50    Male       0    2  Dinner     3         2          0

In [15]:
# sex
a = tips['sex'].unique()
tips['sex_code'] = tips['sex'].replace(dict(zip(a, range(len(a)))))
tips.head(3)

total_bill   tip     sex  smoker  ...  size day_code  time_code  sex_code
0       16.99  1.01  Female       0  ...     2        2          0         0
1       10.34  1.66    Male       0  ...     3        2          0         1
2       21.01  3.50    Male       0  ...     3        2          0         1

[3 rows x 10 columns]

In [16]:
# day
tips['day_code2'] = tips['day'].astype('category').cat.codes
tips.head(3)

total_bill   tip     sex  smoker  ...  day_code time_code  sex_code  day_code2
0       16.99  1.01  Female       0  ...         2         0         0          2
1       10.34  1.66    Male       0  ...         2         0         1          2
2       21.01  3.50    Male       0  ...         2         0         1          2

[3 rows x 11 columns]

In [7]:
#역변환
inversed = encoder.inverse_transform(tips['day'])
inversed

array(['Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun',
       'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun',
       'Sun', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sun', 'Sun', 'Sun', 'Sun',
       'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun', 'Sun',
       'Sun', 'Sun', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Thur', 'Thur', 'Thur', 'Thur',
       'Thur', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur',
       'Thur', 'Fri', 'Fri', 'Fri', 'Fri', 'Fri', 'Fri', 'Fri', 'Fri',
       'Fri', 'Fri', 'Fri', 'Fri', 'Sat', 'Sat', 'Sat', 'Sat', 'Sat',
       'Sat', 'Sat', 'Sat', 'Sat', 'Sat', 'Sun', 'Sun', 'Sun', 'Sun',
       'Sun', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur', 'Thur',
       'Thur',

In [10]:
tips['day_code'] = day_encoded
tips.head(3)

total_bill   tip     sex smoker  day    time  size  day_code
0       16.99  1.01  Female     No    2  Dinner     2         2
1       10.34  1.66    Male     No    2  Dinner     3         2
2       21.01  3.50    Male     No    2  Dinner     3         2

In [ ]:
encoder2 = LabelEncoder()
tips['time_code'] 

### 다른 방법

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr1 = np.arange(1000,9000,1000)
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
data = {'상품':items,'price':arr1}
df = pd.DataFrame(data)
df

상품  price
0     TV   1000
1    냉장고   2000
2  전자레인지   3000
3    컴퓨터   4000
4    선풍기   5000
5    선풍기   6000
6     믹서   7000
7     믹서   8000

In [ ]:
# replace



In [ ]:
# category의 cat.codes


### One_Hot Encoding

In [20]:
import numpy as np
import pandas as pd
from pandas import DataFrame
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [17]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
#숫자값 변환을 위해 LabelEncoder 이용
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[0 1 4 5 3 3 2 2]


In [18]:
#2차원에서 -1은 행또는 열의 갯수를 지정해 주고 나머지를 2차원으로 만든다
#아래는 열의 갯수가 1이므로 8행 1열의 2차원 데이터를 만든다
labels2D = labels.reshape(-1,1)
labels2D

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [21]:
#One-Hot Encoding 적용 (2차원 데이터가 필요함)
one_encoder = OneHotEncoder()
one_encoder.fit(labels2D)
one_labels = one_encoder.transform(labels2D)
print(one_labels)
print(one_labels.toarray())
print('차원', one_labels.shape)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
차원 (8, 6)


In [23]:
##Pandas의 getDummies()를 이용한 One-Hot Encoding
df = DataFrame({'item':items, 'a':list("ABBACCBA")})
df

item  a
0     TV  A
1    냉장고  B
2  전자레인지  B
3    컴퓨터  A
4    선풍기  C
5    선풍기  C
6     믹서  B
7     믹서  A

In [26]:
s = df['item']
pd.get_dummies(s)

TV  냉장고  믹서  선풍기  전자레인지  컴퓨터
0   1    0   0    0      0    0
1   0    1   0    0      0    0
2   0    0   0    0      1    0
3   0    0   0    0      0    1
4   0    0   0    1      0    0
5   0    0   0    1      0    0
6   0    0   1    0      0    0
7   0    0   1    0      0    0

In [27]:
#판다스의 get_dummies 사용시 숫자로 변환없이도 원핫 인코딩이 가능하다. 
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터  a_A  a_B  a_C
0        1         0        0         0           0         0    1    0    0
1        0         1        0         0           0         0    0    1    0
2        0         0        0         0           1         0    0    1    0
3        0         0        0         0           0         1    1    0    0
4        0         0        0         1           0         0    0    0    1
5        0         0        0         1           0         0    0    0    1
6        0         0        1         0           0         0    0    1    0
7        0         0        1         0           0         0    1    0    0

In [28]:
# 일부 범주형에 대해서만 OneHot Encoding을 하고 싶을 경우
temp = df[['item']]
dummy1 = pd.get_dummies(temp)
df2 = pd.concat([df, dummy1], axis=1)
df2

item  a  item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0     TV  A        1         0        0         0           0         0
1    냉장고  B        0         1        0         0           0         0
2  전자레인지  B        0         0        0         0           1         0
3    컴퓨터  A        0         0        0         0           0         1
4    선풍기  C        0         0        0         1           0         0
5    선풍기  C        0         0        0         1           0         0
6     믹서  B        0         0        1         0           0         0
7     믹서  A        0         0        1         0           0         0

In [29]:
a = pd.DataFrame({'x':[1,2,3,1,2,3,1,1,2,2,3]})
pd.get_dummies(a.astype('category'))

x_1  x_2  x_3
0     1    0    0
1     0    1    0
2     0    0    1
3     1    0    0
4     0    1    0
5     0    0    1
6     1    0    0
7     1    0    0
8     0    1    0
9     0    1    0
10    0    0    1

In [ ]:
# datetime type
- dt.year, dt.month, dt.day, dt.hour...
- 요일정보, 공휴일여부

In [ ]:
# 상관계수 df.corr()
- X끼리 상관계수가 높은 경우 : 한 가지를 사용하지 않는 것이 좋음
- 그 둘사이에 정보를 취할 수 있다면 취해서 사용해 보자
  예)  체감온도, 계측상온도 => 온도의 차이값
  예)  키, 몸무게 -> BMI 지수